# Практическое занятие 8
# Компьютерный практикум по алгебре на Python
## Численное решение систем линейных алгебраических уравнений (СЛАУ) с numpy.

https://numpy.org/doc/stable/reference/routines.linalg.html

In [1]:
import numpy as np
from numpy import linalg

### Задание 1.
Решить СЛАУ с помощью linalg.solve() и выполнить проверку.
$$
\left\{
\begin{matrix}
-x+5y-3z=8\\
4x-y+5z=-1\\
3x+4y+5z=10
\end{matrix}
\right.
$$

In [7]:
A = np.array([[-1, 5, -3], [4, -1, 5], [3, 4, 5]])
b = np.array([8, -1, 10])
X = linalg.solve(A, b)
print(f'Решение СЛАУ: {X}')

Решение СЛАУ: [-1.  2.  1.]


### Задание 2.
Определить с помощью Теоремы Кронекера-Капелли и linalg.matrix_rank, совместна ли СЛАУ
$$
\left\{
\begin{matrix}
-x+5y-3z=8\\
4x-y+5z=-1\\
3x+4y+2z=7
\end{matrix}
\right.
$$

Сделать вывод о числе решений (текстом)

In [19]:
A = np.array([[-1, 5, -3], [4, -1, 5], [3, 4, 2]])
b = np.array([8, -1, 7])
Ab = np.column_stack((A, b))
print(f'ранг A = {linalg.matrix_rank(A)}\nранг Ab = {linalg.matrix_rank(Ab)}')

if (linalg.matrix_rank(A) == linalg.matrix_rank(Ab)):
  print('СЛАУ совместна')
else:
  print('СЛАУ несовместна')

array([[-1,  5, -3,  8],
       [ 4, -1,  5, -1],
       [ 3,  4,  2,  7]])

ранг A = 2
ранг Ab = 2
СЛАУ совместна


### Задание 3.
Исследовать на совместность СЛАУ с параметром $a$ при значениях параметра $a=1$ и $a=-1$ и найти решение, если оно единственно и провести проверку подстановкой.
$$
\left\{
\begin{matrix}
-x+5y-3z=8a\\
4x-ay+5z=-a\\
3x+4y+2z=5a
\end{matrix}
\right.
$$

In [16]:
print('a = 1:')
A = np.array([[-1, 5, -3], [4, -1, 5], [3, 4, 2]])
b = np.array([8 * 1, -1, 5 * 1])
Ab = np.column_stack((A, b))

print(f'ранг A = {linalg.matrix_rank(A)}\nранг Ab = {linalg.matrix_rank(Ab)}')

if (linalg.matrix_rank(A) == linalg.matrix_rank(Ab)):
  print('СЛАУ совместна')
else:
  print('СЛАУ несовместна')

a = 1:
ранг A = 2
ранг Ab = 3
СЛАУ несовместна


In [17]:
print('a = -1:')
A = np.array([[-1, 5, -3], [4, -(-1), 5], [3, 4, 2]])
b = np.array([8 * (-1), -(-1), 5 * (-1)])
Ab = np.column_stack((A, b))

print(f'ранг A = {linalg.matrix_rank(A)}\nранг Ab = {linalg.matrix_rank(Ab)}')

if (linalg.matrix_rank(A) == linalg.matrix_rank(Ab)):
  print('СЛАУ совместна')
else:
  print('СЛАУ несовместна')

a = -1:
ранг A = 3
ранг Ab = 3
СЛАУ совместна


### Задание 4
В расширенной матрице СЛАУ из Задания 2 

1) выделить матрицу левой части

2) выделить столбец правой части

3) транспонировать матрицу, полученную в 1)

4) получить расширенную матрицу из матрицы 3) и столбца 2)

5) создать на основе списочного выражения np.array $3\times 4$ из расположенных в шахматном порядке чисел 1 и $-1$.

In [36]:
Ab = np.array([[-1, 5, -3, 8], [4, -1, 5, -1], [3, 4, 2, 7]])
A = Ab[:, :-1]
display(A)
print('\n')

b = Ab[:, -1]
display(b)
print('\n')

A_t = np.transpose(A)
display(A_t)
print('\n')

Ab = np.column_stack((A, b))
display(Ab)
print('\n')

Q = np.array([[2 * (((i + j + 1) % 2)) - 1 for i in range(4)] for j in range(3)])
display(Q)

array([[-1,  5, -3],
       [ 4, -1,  5],
       [ 3,  4,  2]])

array([ 8, -1,  7])

array([[-1,  4,  3],
       [ 5, -1,  4],
       [-3,  5,  2]])

array([[-1,  5, -3,  8],
       [ 4, -1,  5, -1],
       [ 3,  4,  2,  7]])

array([[ 1, -1,  1, -1],
       [-1,  1, -1,  1],
       [ 1, -1,  1, -1]])

### Индивидуальное задание.
Исследовать на совместность СЛАУ с параметром $a$ при заданных значениях параметра $a$ и найти решение, если оно единственно и провести проверку подстановкой.
 

In [42]:
#126
print('a = -7:')
A = np.array([[-9, -1, -1, -6], [-7, 5, 4, 4], [1, -3, -4, -8], [12, -16, -13, -18]])
b = np.array([-87, -75, 5, 162])

Ab = np.column_stack((A, b))
print(f'ранг A = {linalg.matrix_rank(A)}\nранг Ab = {linalg.matrix_rank(Ab)}')

if (linalg.matrix_rank(A) == linalg.matrix_rank(Ab)):
  print('СЛАУ совместна')
else:
  print('СЛАУ несовместна')



a = -7:
ранг A = 3
ранг Ab = 4
СЛАУ несовместна


In [43]:
print('a = -6:')
A = np.array([[-9, -1, -1, -6], [-6, 5, 4, 4], [1, -3, -4, -8], [12, -16, -13, -18]])
Ab = np.column_stack((A, b))
print(f'ранг A = {linalg.matrix_rank(A)}\nранг Ab = {linalg.matrix_rank(Ab)}')

if (linalg.matrix_rank(A) == linalg.matrix_rank(Ab)):
  print('СЛАУ совместна')
else:
  print('СЛАУ несовместна')

X = linalg.solve(A, b)
print(f'Решение СЛАУ: {X}')

a = -6:
ранг A = 4
ранг Ab = 4
СЛАУ совместна
Решение СЛАУ: [ 8. -7. -2.  4.]
